In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
from random import randint

In [2]:
artists = pd.read_csv("Data/hetrec2011-lastfm-2k/artists.dat", delimiter='\t')
tags = pd.read_csv("Data/hetrec2011-lastfm-2k/tags.dat", delimiter='\t', encoding = "latin-1")
userArt = pd.read_csv("Data/hetrec2011-lastfm-2k/user_artists.dat", delimiter='\t')
userFrd = pd.read_csv("Data/hetrec2011-lastfm-2k/user_friends.dat", delimiter='\t')
userTAT = pd.read_csv("Data/hetrec2011-lastfm-2k/user_taggedartists-timestamps.dat", delimiter='\t')
userTA = pd.read_csv("Data/hetrec2011-lastfm-2k/user_taggedartists.dat", delimiter='\t')

In [3]:
artistlist = []
for i in range(userArt.shape[0]):
    if userArt['artistID'][i] not in artistlist:
        artistlist.append(userArt['artistID'][i])
artistlist.sort()

In [4]:
userlist = []
for i in range(userArt.shape[0]):
    if userArt['userID'][i] not in userlist:
        userlist.append(userArt['userID'][i])

In [5]:
testDF = pd.read_csv("./Data/evaluationMatrix2.csv", index_col=0)

In [6]:
testDF

0     1      2    3    4      5      6      7    8    9  ...    17622  \
0     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
2     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
3     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
4     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
5     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
6     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
7     0.0   0.0    0.0  0.0  0.0    0.0    0.0  587.0  0.0  0.0  ...      0.0   
8     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
9     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
10    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
11    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
12    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
13    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
14    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
15    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
16    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
17    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
18    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
19    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
20    0.0   0.0    0.0  0.0  0.0    0.0  212.0    0.0  0.0  0.0  ...      0.0   
21    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
22    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
23    0.0   0.0    0.0  0.0  0.0  550.0    0.0    0.0  0.0  0.0  ...      0.0   
24    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
25    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
26    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
27    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
28    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
29    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
...   ...   ...    ...  ...  ...    ...    ...    ...  ...  ...  ...      ...   
1862  0.0  83.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1863  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1864  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1865  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1866  0.0   0.0    0.0  0.0  0.0    0.0  399.0    0.0  0.0  0.0  ...      0.0   
1867  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1868  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1869  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1870  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1871  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1872  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1873  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1874  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1875  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1876  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1877  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1878  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1879  0.0   0.0    0.0  0.0  0.0    0.0

In [162]:
testCP = testDF.copy()

## Método que usa um Knn

In [164]:
nbrs = NearestNeighbors(leaf_size=50, n_neighbors=3).fit(testCP)

In [165]:
distances, indices = nbrs.kneighbors(testCP)

In [166]:
indices

array([[   0, 1686, 1097],
       [   1, 1706, 1708],
       [   2,  528,  461],
       ..., 
       [1889, 1005,   98],
       [1890, 1792, 1708],
       [1891,  548,  196]])

In [250]:
testCP2 = testCP.copy()
mylisttest = []
for i in range(17632):
    mylisttest.append(0)
for i in range(100):
    rpos = randint(0,17632)
    rvalue = randint(0,500)
    mylisttest[rpos] = rvalue
mylisttest = pd.DataFrame(list(zip(mylisttest)),columns=['a'])

In [254]:
neighbors = nbrs.kneighbors([mylisttest['a']])
neighbors

(array([[ 2815.16269512,  2816.60061067,  2816.64694273]]),
 array([[ 117,   32, 1147]]))

In [275]:
mostSimilarPref = testCP2.T[neighbors[1][0][0]]
mspo = mostSimilarPref.sort_values(ascending=False)
mlto = mylisttest.sort_values(['a'],ascending=False).reset_index()

similars = []
for i in range(len(mylisttest)):
    if mylisttest['a'][i] > 0:
        if mostSimilarPref[i] > 0:
            similars.append(i)
similars

[580, 2982]

In [276]:
recomendation = 0
for i in range(len(mostSimilarPref)):
    if mostSimilarPref[i] > recomendation:
        if mostSimilarPref[i] not in similars:
            recomendation = mostSimilarPref[i]
recID = artistlist[int(recomendation)]
artistaRecomendado = "Nenhum"
for i in range(len(artists)):
    if artists['id'][i] == recID:
        artistaRecomendado = artists['name'][i]
        break
artistaRecomendado

'Dawn of Ashes'

## Método que retorna o usuário que possui mais preferências dentre as maiores preferências fornecidas

#### Meio que um brute force, mas dava pra ser ainda mais bruto

In [289]:
testRec = testCP.copy()
testRecAux = []
similars2 = []
for i in range(len(mlto)):
    if mlto['a'][i] > 0:
        testRecAux = testRec.copy()
        testRec = testRec.drop(testRec[testRec[testRec.columns[int(mlto.index[i])]] < 1].index)
        if len(testRec) == 0:
            testRec = testRecAux.copy()
        else:
            similars2.append(mlto['a'][i])
    else:
        break
testRec

0    1    2    3    4    5      6      7    8    9  ...    17622  \
256  483.0  0.0  0.0  0.0  0.0  0.0  216.0  175.0  0.0  0.0  ...      0.0   

     17623  17624  17625  17626  17627  17628  17629  17630  17631  
256    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[1 rows x 17632 columns]

In [290]:
similars2

[495, 444, 433, 161]

In [293]:
testCP3 = testCP.copy()
mostSimilarPref2 = testCP3.T[testRec.index[0]]
recomendation = 0
for i in range(len(mostSimilarPref)):
    if mostSimilarPref2[i] > recomendation:
        if mostSimilarPref2[i] not in similars2:
            recomendation = mostSimilarPref2[i]
recID = artistlist[int(recomendation)]
artistaRecomendado = "Nenhum"
for i in range(len(artists)):
    if artists['id'][i] == recID:
        artistaRecomendado = artists['name'][i]
        break
artistaRecomendado

'Max Tannone'