In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
from random import randint

In [2]:
artists = pd.read_csv("Data/hetrec2011-lastfm-2k/artists.dat", delimiter='\t')
tags = pd.read_csv("Data/hetrec2011-lastfm-2k/tags.dat", delimiter='\t', encoding = "latin-1")
userArt = pd.read_csv("Data/hetrec2011-lastfm-2k/user_artists.dat", delimiter='\t')
userFrd = pd.read_csv("Data/hetrec2011-lastfm-2k/user_friends.dat", delimiter='\t')
userTAT = pd.read_csv("Data/hetrec2011-lastfm-2k/user_taggedartists-timestamps.dat", delimiter='\t')
userTA = pd.read_csv("Data/hetrec2011-lastfm-2k/user_taggedartists.dat", delimiter='\t')

In [3]:
artistlist = []
for i in range(userArt.shape[0]):
    if userArt['artistID'][i] not in artistlist:
        artistlist.append(userArt['artistID'][i])
artistlist.sort()

In [4]:
userlist = []
for i in range(userArt.shape[0]):
    if userArt['userID'][i] not in userlist:
        userlist.append(userArt['userID'][i])

In [5]:
testDF = pd.read_csv("./Data/evaluationMatrix2.csv", index_col=0)

In [6]:
testDF

0     1      2    3    4      5      6      7    8    9  ...    17622  \
0     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
2     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
3     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
4     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
5     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
6     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
7     0.0   0.0    0.0  0.0  0.0    0.0    0.0  587.0  0.0  0.0  ...      0.0   
8     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
9     0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
10    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
11    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
12    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
13    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
14    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
15    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
16    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
17    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
18    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
19    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
20    0.0   0.0    0.0  0.0  0.0    0.0  212.0    0.0  0.0  0.0  ...      0.0   
21    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
22    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
23    0.0   0.0    0.0  0.0  0.0  550.0    0.0    0.0  0.0  0.0  ...      0.0   
24    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
25    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
26    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
27    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
28    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
29    0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
...   ...   ...    ...  ...  ...    ...    ...    ...  ...  ...  ...      ...   
1862  0.0  83.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1863  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1864  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1865  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1866  0.0   0.0    0.0  0.0  0.0    0.0  399.0    0.0  0.0  0.0  ...      0.0   
1867  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1868  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1869  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1870  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1871  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1872  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1873  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1874  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1875  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1876  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1877  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1878  0.0   0.0    0.0  0.0  0.0    0.0    0.0    0.0  0.0  0.0  ...      0.0   
1879  0.0   0.0    0.0  0.0  0.0    0.0

In [7]:
testCP = testDF.copy()

## Método que usa um Knn

In [8]:
nbrs = NearestNeighbors(leaf_size=50, n_neighbors=3).fit(testCP)

In [9]:
distances, indices = nbrs.kneighbors(testCP)

In [10]:
indices

array([[   0, 1686, 1097],
       [   1, 1706, 1708],
       [   2,  528,  461],
       ..., 
       [1889, 1005,   98],
       [1890, 1792, 1708],
       [1891,  548,  196]])

In [206]:
testCP2 = testCP.copy()
mylisttest = []
for i in range(17632):
    mylisttest.append(0)
for i in range(20):
    rpos = randint(0,17632)
    rvalue = randint(0,1000)
    mylisttest[rpos] = rvalue
mylisttest = pd.DataFrame(list(zip(mylisttest)),columns=['a'])

In [207]:
neighbors = nbrs.kneighbors([mylisttest['a']])
neighbors

(array([[ 2485.6805909 ,  2485.99356395,  2485.99416733]]),
 array([[1190, 1708, 1209]]))

In [208]:
mostSimilarPref = testCP2.T[neighbors[1][0][0]]
mspo = mostSimilarPref.sort_values(ascending=False)
mlto = mylisttest.sort_values(['a'],ascending=False).reset_index()

similars = []
for i in range(len(mylisttest)):
    if mylisttest['a'][i] > 0:
        if mostSimilarPref[i] > 0:
            similars.append(i)
similars

[13211]

In [209]:
recomendation = 0
for i in range(len(mostSimilarPref)):
    if mostSimilarPref[i] > recomendation:
        if mostSimilarPref[i] not in similars:
            recomendation = mostSimilarPref[i]
recID = artistlist[int(recomendation)]
artistaRecomendado = "Nenhum"
for i in range(len(artists)):
    if artists['id'][i] == recID:
        artistaRecomendado = artists['name'][i]
        break
artistaRecomendado

'xotox'

## Método que retorna o usuário que possui mais preferências dentre as maiores preferências fornecidas

#### Meio que um brute force, mas dava pra ser ainda mais bruto

In [210]:
testRec = testCP.copy()
testRecAux = []
similars2 = []
for i in range(len(mlto)):
    if mlto['a'][i] > 0:
        testRecAux = testRec.copy()
        testRec = testRec.drop(testRec[testRec[testRec.columns[int(mlto['index'][i])]] < 1].index)
        if len(testRec) == 0:
            testRec = testRecAux.copy()
        else:
            similars2.append(mlto['a'][i])
    else:
        break
testRec

0      1    2    3      4    5       6    7      8    9  ...    17622  \
528   0.0    0.0  0.0  0.0    0.0  0.0     0.0  0.0    0.0  0.0  ...      0.0   
877   0.0    0.0  0.0  0.0    0.0  0.0     0.0  0.0    0.0  0.0  ...      0.0   
1289  0.0    0.0  0.0  0.0    0.0  0.0     0.0  0.0    0.0  0.0  ...      0.0   
1400  0.0  868.0  0.0  0.0  653.0  0.0  1025.0  0.0  663.0  0.0  ...      0.0   

      17623  17624  17625  17626  17627  17628  17629  17630  17631  
528     0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
877     0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1289    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1400    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[4 rows x 17632 columns]

In [212]:
similars2

[982]

In [213]:
testCP3 = testCP.copy()
mostSimilarPref2 = testCP3.T[testRec.index[0]]
recomendation = 0
for i in range(len(mostSimilarPref)):
    if mostSimilarPref2[i] > recomendation:
        if mostSimilarPref2[i] not in similars2:
            recomendation = mostSimilarPref2[i]
recID = artistlist[int(recomendation)]
artistaRecomendado = "Nenhum"
for i in range(len(artists)):
    if artists['id'][i] == recID:
        artistaRecomendado = artists['name'][i]
        break
artistaRecomendado

'Lifetime'

## Método mais brute force

In [214]:
ua2 = userArt.copy()
ua2 = ua2.sort_values(['weight'],ascending=False).reset_index(drop=True).groupby(['userID'], sort=False)
ua2.get_group(88)

userID  artistID  weight
72140      88      1947      94
77274      88      2398      68
78727      88      2399      61
79774      88       859      55
80277      88      2400      53
80507      88       159      52
80635      88      2280      51
82417      88       204      42
82447      88      2401      42
83348      88      2402      38
83877      88       211      35
84125      88       433      34
85041      88      2403      29
85308      88      2404      28
85311      88      2405      28
85393      88       622      28
86234      88      2406      24
86482      88      2407      23
86696      88      2277      22
86846      88      2408      21
88169      88       196      15
88564      88      2409      14
88614      88       440      14
89095      88      1732      12
89096      88       210      12
89106      88      2410      12
89107      88      2411      12
89812      88      2414       9
89813      88      2413       9
89814      88      2412       9
89826      88       629       9
90152      88      2415       8
90186      88      2416       7
90225      88      2417       7
90393      88       199       7
90419      88      1242       7
90719      88      2418       6
90915      88       223       5
90940      88      2420       5
90949      88      2419       5
90952      88      2421       5
90954      88      2422       5
90955      88      2423       5
91413      88      2425       4
91417      88       592       4
91422      88       863       4
91424      88      1944       4
91426      88      2424       4
91514      88       154       3
91517      88       630       3

In [215]:
mlto3 = mlto.copy()
mlto3 = mlto3.drop(mlto3[mlto3['a'] < 1].index)
mlto3

index    a
0    7956  982
1    1599  955
2    4824  846
3    8271  837
4     573  833
5    2729  791
6    5710  668
7    4687  482
8   12899  423
9    4599  413
10  12693  362
11  13211  362
12    629  332
13   3546  304
14   5209  193
15   6343  149
16   8333  105
17  12104   67
18  11083   13
19  15061    7

In [225]:
maior = 0
maiorUser = 0
score = 0
tamanho = len(mlto3)
valorMaior = mlto3['a'][0]
valorMenor = mlto3['a'][len(mlto3)-1]
for i in range(len(userlist)):
    score = 0
    ua3 = ua2.get_group(userlist[i]).copy().reset_index(drop=True)
    for j in range(len(mlto3)):
        for k in range(len(ua3)):
            if mlto3['index'][j] == ua3['artistID'][k]:
                score = score + ua3['weight'][k]*(mlto3['a'][j]/valorMaior)
    if score > maior:
        maior = score
        maiorUser = i

In [226]:
maior

1373.2423625254582

In [227]:
maiorUser

237

In [220]:
userlist[237]

254

In [221]:
ua2.get_group(254)

userID  artistID  weight
2290      254      4820    3817
2355      254      4821    3744
3668      254      4822    2743
5358      254      4375    2108
6856      254      4823    1742
6951      254      1513    1724
7697      254      4824    1594
8317      254      4825    1508
8453      254      1045    1490
9037      254      4826    1414
10673     254      4827    1240
10769     254      4828    1231
12236     254       857    1112
13684     254      4829    1021
14126     254       412     996
14172     254       840     993
14590     254      4830     965
14933     254      4831     943
18446     254      4157     769
18724     254      1406     758
19316     254      4832     736
20198     254      1645     706
20633     254      4833     690
21286     254      4834     668
21559     254      4835     660
23087     254      1866     617
23383     254      4836     609
25580     254      4837     555
25708     254      4434     552
27216     254      4838     520
27369     254      4839     517
27863     254      4840     506
27942     254      4841     504
28043     254      4842     502
28724     254      4087     489
29232     254      4843     479
29336     254      4844     478
29509     254       808     474
29667     254      4845     471
29718     254      4846     470
30032     254      1046     465
30415     254      4218     458
30678     254       227     453
31691     254      3398     436
32160     254      4847     429
33491     254      1186     408
35469     254      4848     381
36318     254      4849     369
36466     254      4850     367
37120     254      4851     359

In [222]:
mlto3

index    a
0    7956  982
1    1599  955
2    4824  846
3    8271  837
4     573  833
5    2729  791
6    5710  668
7    4687  482
8   12899  423
9    4599  413
10  12693  362
11  13211  362
12    629  332
13   3546  304
14   5209  193
15   6343  149
16   8333  105
17  12104   67
18  11083   13
19  15061    7

13873

In [224]:
ua4 = ua2.get_group(254).copy().reset_index(drop=True)
similars3 = []
for i in range(len(mlto3)):
    for j in range(len(ua4)):
        if mlto3['index'][i] == ua4['artistID'][j]:
                   similars3.append(ua4['artistID'][j])
similars3

[4824]

In [195]:
mlto3['index'][0]

678